Fixed oscillation in conference AGC processing. Especially during volume reduction processing
signalwire/freeswitch pull request #1064
Opened 2021-02-04 05:04 UTC by figaro2015

https://github.com/signalwire/freeswitch/issues/1011

2021-02-04 18:49 UTC, crienzo requested changes
Can this be fixed without changing switch_normalize_volume_granular()?

2021-02-04 19:04 UTC, crienzo commented on src/mod/applications/mod_conference/conference_api.c
> -
This should be if (argv[3]) {

2021-02-04 19:05 UTC, crienzo commented on src/mod/applications/mod_conference/conference_api.c
> -	if (argv[0]) {
if (argv[3]) {

2021-02-04 19:05 UTC, crienzo commented on src/mod/applications/mod_conference/conference_api.c
> -		tmp = atoi(argv[0]);
tmp = atoi(argv[3]);

2021-02-04 21:26 UTC, figaro2015 commented
Actually, my main change is not in the switch_normalize_volume_granular(), but in switch_change_sln_volume_granular().
The main reason for the oscillation is the fact that the step in the array of coefficients for the negative adjustment is too wide. In other words, it is not 'granular' enough. Which causes, on every run of the algorithm, to force the adjustment either to increase or decrease the volume. But the actual AGC processing algorithm is correct is working fine.
Also, I had to increase the margin value to 100. 
These adjustments seem to produce acceptable results in AGC processing. To accommodate even more fine margin (20, etc) the array of negative coefficients will have to be increased even further, with the smaller step between the elements.

2021-02-05 01:11 UTC, crienzo commented
How about calculating amplitude gain from dB like:
```
#define dB_gain_factor(gain_dB) (powf(10.0f, (float)gain_dB / 20.0f))
```
Then we get 2x perceived volume increase for every +10 increase in gain_dB.  Then you can be as granular as you want to be.

2021-02-13 21:03 UTC, crienzo commented
@figaro2015 I rescaled the tables for the granular volume.  Looks like they are still pretty close- can you verify this works for you?  Thanks.

2021-02-15 21:52 UTC, figaro2015 commented
Chris, I believe the coefficients you generated are working fine. Please see the screenshot of the Audacity plot attached.

![Latest_AGC](https://user-images.githubusercontent.com/11821347/107996294-e7d0dd00-6f94-11eb-8427-988fe553403b.png)

2021-02-25 15:30 UTC, crienzo commented
@andywolk I think we can take this now

2021-02-25 15:30 UTC, crienzo approved these changes

2021-04-02 19:17 UTC, andywolk approved these changes

2021-04-02 19:18 UTC, merged

2021-04-10 18:20 UTC, MarioG-X commented
I think it's possible that this change broke building make now fails. I was able to build on March 24, but not on April 3. Using git log the only change between the two is this issue. Please see issue #1145.

git log:
commit ec1a0215fedb56bcd6f73fb1e93f763ed5286cbb (HEAD -> master, origin/master, origin/HEAD)
Author: figaro2015 <figaro2015@users.noreply.github.com>
Date:   Fri Apr 2 12:18:16 2021 -0700

    [Core, mod_conference] Fixed oscillation in conference AGC processing. Especially during volume reduction processing ( 1 0 6 4)
    * Fixed oscillation in conference AGC processing. Especially during volume reduction processing    
    * Re-scaled granular volume to +/- 50 dB level change. 10 = double loudness, -10 = half loudness, 0 = no change
    Co-authored-by: Chris Rienzo <chris@signalwire.com>
commit 67cec5c3e80e653d4540b9ba2c4a0b38b92a9458
Author: Andrey Volk <andywolk@gmail.com>
Date:   Thu Mar 25 18:52:56 2021 +0300
    version bump