mod_verto: add context into msg event header
signalwire/freeswitch pull request #1554
Opened 2022-02-22 10:12 UTC by wmasilva

resolves 1553

2022-02-22 13:06 UTC, dragos-oancea commented
lgtm

2023-04-18 16:55 UTC, andywolk requested changes

2023-04-18 16:55 UTC, andywolk commented on src/mod/endpoints/mod_verto/mod_verto.c
> +		switch_mutex_unlock(jsock->flag_mutex);
Missing new line after an `if` block

2023-04-18 16:55 UTC, andywolk commented on src/mod/endpoints/mod_verto/mod_verto.c
> +		switch_mutex_lock(jsock->flag_mutex);
Requires a new line after declarations.

2023-08-11 16:37 UTC, andywolk approved these changes

2023-08-11 17:08 UTC, merged