FIX #1762 update switch_apr.c for openssl3
signalwire/freeswitch pull request #1767
Opened 2022-08-21 12:12 UTC by jpfox156

Low-level openssl api for accessing md5 was deprecated in openssl3.0, leading to errors during compile of freeswitch. 
Update switch_md5 method to use the openssl high-level api. 
syntax plagiarized from: 
https://stackoverflow.com/questions/69806220/advice-needed-for-migration-of-low-level-openssl-api-to-high-level-openssl-apis

2022-12-26 22:09 UTC, ar45 commented
@jpfox156 Can you rebase this?

2022-12-30 17:08 UTC, ar45 approved these changes

2022-12-30 17:08 UTC, ar45 commented
@andywolk Can you please review this?

2023-01-18 12:46 UTC, andywolk requested changes

2023-01-18 12:46 UTC, andywolk commented on src/switch_apr.c
> +		// MD5_Init
Please use `/* */` comment style

2023-01-18 12:46 UTC, andywolk commented on src/switch_rtp.c
> +	}
A new line after an `if` block is required.

2023-01-19 12:50 UTC, andywolk commented on src/switch_core_cert.c
> +		ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_RSA, NULL);
A new line after declarations is required.

2023-01-19 12:50 UTC, andywolk commented on src/switch_core_cert.c
> +		/* Generate key */
A new line after an if block

2023-01-19 12:50 UTC, andywolk commented on src/switch_core_cert.c
> +		EVP_PKEY_CTX_free(ctx);
A new line after an if block

2023-01-19 12:51 UTC, andywolk commented on src/switch_rtp.c
> +
We can skip that new line

2023-02-06 20:29 UTC, daniel-lucio commented
What is preventing this to be accepted?

2023-07-06 12:51 UTC, xadhoom commented
With the current changes FS may segfault, depending on openssl 3 config.

The crash happens because the call to `mkcert` in `switch_core_gen_certs` is not checked on return value, and if the return value is 0 (which means that certs/keys gen have failed) the pointers are not set but still passed to `PEM_write_PrivateKey` which segfaults if `pkey` is not set.

The reason why `mkcert` fails is because (at least on rhel9) `EVP_sha1` is deprecated which fails `X509_sign`.

So I suggest two addtions:
- check retval for `mkcert` in `switch_core_gen_certs`, something like:
```patch
-	mkcert(&x509, &pkey, 4096, 0, 36500);
+	if (!mkcert(&x509, &pkey, 4096, 0, 36500)) {
+		switch_log_printf(SWITCH_CHANNEL_LOG, SWITCH_LOG_ERROR, "Certificate generation failed\n");
+		abort();
+	}

```

then switch to `EVP_sha256` when signing the certificate in `mkcert`, something like:
```patch
 	 */
 	X509_set_issuer_name(x, name);
 
+#if OPENSSL_VERSION_NUMBER >= 0x30000000
+	if (!X509_sign(x, pk, EVP_sha256()))
+#else
 	if (!X509_sign(x, pk, EVP_sha1()))
+#endif
 		goto err;
 
 	*x509p = x;
 	*pkeyp = pk;
 	return(1);
  err:
+	ERR_print_errors_fp(stdout);
 	return(0);
 }
 
```

Note that I've added also a call to `ERR_print_errors_fp` on the `err` label in order to help diagnose.

2023-07-24 18:20 UTC, mjerris approved these changes

2023-07-24 18:56 UTC, merged