[mod_commands] Fix and improve coalesece function
signalwire/freeswitch pull request #1843
Opened 2022-10-27 16:21 UTC by greenbea

* fixed memory leak
* added custom delimeter support
* fixed return value

2022-11-01 13:34 UTC, dragos-oancea submitted a review, later dismissed

2022-11-01 15:01 UTC, greenbea commented
I would you use it for something like setting an emergency caller id number
```
<action application="set" data="effective_caller_id_number=${coalsece ${emergency_caller_id_number},${outbound_caller_id_number}}"
```

2023-03-21 16:10 UTC, andywolk requested changes

2023-03-21 16:10 UTC, andywolk commented on src/mod/applications/mod_commands/mod_commands.c
> +	switch_safe_free(mydata);
Our coding guidelines require a new line before return.

2023-03-21 17:00 UTC, andywolk approved these changes

2023-03-27 11:47 UTC, dragos-oancea approved these changes

2023-03-27 17:03 UTC, merged