[mod_amqp] Event subclass support
signalwire/freeswitch pull request #1996
Opened 2023-03-19 20:46 UTC by greenbea

Adds support to subscribe to CUSTOM events with specific subclasses by using the `event_filter` with ^ as a delimiter between the event and the subclass.

example:
```xml
<param name="event_filter" value="SWITCH_EVENT_CUSTOM^sofia::register" />
```

2023-03-21 16:08 UTC, briankwest submitted a review, later dismissed

2023-03-21 16:11 UTC, andywolk requested changes

2023-03-21 18:52 UTC, greenbea commented on src/mod/event_handlers/mod_amqp/mod_amqp_producer.c
> +					}
I added a newline.

2023-03-27 16:54 UTC, andywolk approved these changes

2023-03-27 16:55 UTC, merged