[mod_kazoo] Coverity fixes
signalwire/freeswitch pull request #2043
Opened 2023-04-14 16:50 UTC by jakubkarolczyk

2023-04-14 16:54 UTC, lazedo requested changes

2023-04-14 16:54 UTC, lazedo commented on src/mod/event_handlers/mod_kazoo/kazoo_message.c
> +			switch_safe_free(expanded);
this is wrong

2023-04-14 16:57 UTC, jakubkarolczyk commented on src/mod/event_handlers/mod_kazoo/kazoo_message.c
> +			switch_safe_free(expanded);
why you think this is wrong?

2023-04-14 17:04 UTC, jakubkarolczyk commented on src/mod/event_handlers/mod_kazoo/kazoo_message.c
> +			switch_safe_free(expanded);
ok, I see

2023-04-17 10:53 UTC, andywolk approved these changes

2023-04-17 10:53 UTC, merged

2023-10-30 10:25 UTC, ivanuschak commented
It looks like this fix causes crash on data kazoo exchange (on the service startup when FreeSwitch receives XML data from kazoo).
When the memory for the string `xml_str` is already freed [at this line](https://github.com/signalwire/freeswitch/blob/master/src/mod/event_handlers/mod_kazoo/kazoo_node.c#L1151), [another thread](https://github.com/signalwire/freeswitch/blob/master/src/mod/event_handlers/mod_kazoo/kazoo_fetch_agent.c#L315) is using this string to parse XML, and it causes crash when FreeSwitch is trying to parse XML from this released memory 

`2023-10-30 09:30:37.017722 98.37% [DEBUG] kazoo_fetch_agent.c:369 Sending configuration XML request (dec5f565-3108-48ae-9d38-1af699b210d0) to ecallmgr@ippbx.dev.esrp.or.nga911.com <1.3411.94>
2023-10-30 09:30:37.017722 98.37% [DEBUG] kazoo_node.c:1548 Sent erlang message to ecallmgr@ippbx.dev.esrp.or.nga911.com <1.3411.94>
2023-10-30 09:30:37.017722 98.37% [DEBUG] kazoo_fetch_agent.c:444 Received configuration XML (dec5f565-3108-48ae-9d38-1af699b210d0) after 0ms: ºú{𿊲2023-10-30 09:30:37.017722 98.37% [ERR] switch_xml.c:1800 Error[[error near line 1]: root tag missing]`