mod_python3: fix build on Python 3.10+
signalwire/freeswitch pull request #2146
Opened 2023-07-06 11:47 UTC by linuxmaniac

fix #2145

2023-07-06 16:03 UTC, andywolk requested changes

2023-07-10 16:43 UTC, andywolk commented on src/mod/languages/mod_python3/mod_python3.c
> +			sprintf((char*)sTemp, "\n\tFile: \"%s\", line %i, in %s",
`sizeof` would be better and there is a misisng new line after the `if` block still.

2023-07-10 17:22 UTC, linuxmaniac commented on src/mod/languages/mod_python3/mod_python3.c
> +			sprintf((char*)sTemp, "\n\tFile: \"%s\", line %i, in %s",
@andywolk is that what you want?

2023-07-10 18:14 UTC, andywolk commented on src/mod/languages/mod_python3/mod_python3.c
> +			sprintf((char*)sTemp, "\n\tFile: \"%s\", line %i, in %s",
Perfect. Thank you!

2023-07-11 14:50 UTC, merged