[mod_amqp] Adjusting to Appropriate Log Level for Message
signalwire/freeswitch pull request #2149
Opened 2023-07-07 09:56 UTC by mahald

Refined Logging Level for FreeSWITCH's mod_amqp: The logging level for the AMQP module in FreeSWITCH has been updated from 'warning' to 'debug'. This adjustment ensures a more suitable level for the log message and eliminates any potential impact on production environments. Previously, the 'warning' level would lead to unnecessary log entries for each individual message, although there was no actual warning condition. This change improves logging efficiency and appropriateness for mod_amqp's operations within FreeSWITCH.

2023-07-07 11:13 UTC, mahald commented
Dear Team,

I hope this message finds you well. I am writing in response to the recent unit test failures that occurred in the context of the current pull request.

Upon careful evaluation of the situation, I would like to bring to your attention that these failures seem to be independent of the recent changes proposed in the pull request. From my understanding, the observed test failures are not directly tied to the modifications put forth in this PR.

It appears that these particular unit tests have a tendency to intermittently fail, or perhaps even fail persistently, irrespective of the changes committed. Consequently, this issue seems to reflect a broader problem within our testing environment rather than being a direct result of the proposed alterations.

Given this situation, I kindly ask the team to investigate these specific unit test failures further. Your input will significantly help to resolve this issue and ensure that our testing processes are consistent, reliable, and effective.

Once the team has addressed these test failures, I would appreciate if the pull request could be reevaluated in light of these findings.

Thank you for your understanding and attention to this matter. I look forward to your feedback and assistance in this regard.

Best regards, mahald

2024-01-10 09:30 UTC, mahald commented
Can some merge this? it's a very minor change but keeps filling my log on live system since it's the only warning that is logging while it's not a warning.

2024-01-10 10:07 UTC, jakubkarolczyk requested changes
Please change the log severity to DEBUG1

2024-01-10 11:22 UTC, mahald commented
ok, changed to SWITCH_LOG_DEBUG1 @jakubkarolczyk

2024-01-10 11:55 UTC, jakubkarolczyk approved these changes

2024-01-10 16:01 UTC, merged