[mod_logfile] add logfile open error log and fixes a missing \n
signalwire/freeswitch pull request #2190
Opened 2023-08-05 02:45 UTC by seven1240

2023-08-05 16:08 UTC, tanyingyu commented
Yes

2023-08-10 09:44 UTC, andywolk requested changes

2023-08-10 09:44 UTC, andywolk commented on src/mod/loggers/mod_logfile/mod_logfile.c
>  		return SWITCH_STATUS_FALSE;
LGTM except a new line before return is missing here.

2023-08-11 11:21 UTC, andywolk approved these changes

2023-08-11 11:21 UTC, merged