[mod_amr, mod_amrwb] Fix input data corruption
signalwire/freeswitch pull request #2369
Opened 2024-01-23 12:58 UTC by dkunilov

Two similar problems with AMR and AMRWB are fixed here:
1. decode() function calls switch_amr_unpack_be/switch_amr_unpack_oa which unpacks the data in-place, thus corrupting the frame being decoded. If a READ media bug is present in the session (e.g. when using record_session), the same incoming AMR frame is decoded twice: first time for passing to the media bug and second time for passing to B-party. This results to the recorded audio being clear, but B-party hearing a distorted sound. This is described in #2134 .
The solution is to work on a copy of original encoded data.
2. init() function calls switch_separate_string() on codec->fmtp_in, which corrupts the fmtp string as a side effect. So when switch_core_codec_copy() is called, the resulting copy has different settings. The solution is to work on a copy of fmtp_in like other codecs do.

2024-01-23 16:37 UTC, dragos-oancea approved these changes

2024-01-23 17:43 UTC, andywolk requested changes

2024-01-23 17:43 UTC, andywolk commented on src/mod/codecs/mod_amrwb/mod_amrwb.c
> +	memcpy(buf, encoded_data, encoded_data_len);
Potential stack overflow if `encoded_data_len > SWITCH_AMRWB_OUT_MAX_SIZE` by any reason.

2024-01-24 09:34 UTC, dkunilov commented on src/mod/codecs/mod_amrwb/mod_amrwb.c
> +	memcpy(buf, encoded_data, encoded_data_len);
As input frames are never supposed to be larger than SWITCH_AMRWB_OUT_MAX_SIZE and it is really an error case, would you be okay with returning SWITCH_STATUS_FALSE and not processing such frames?

2024-01-24 09:40 UTC, andywolk commented on src/mod/codecs/mod_amrwb/mod_amrwb.c
> +	memcpy(buf, encoded_data, encoded_data_len);
Yeah. Let's drop it.

2024-01-24 11:07 UTC, dkunilov commented on src/mod/codecs/mod_amrwb/mod_amrwb.c
> +	memcpy(buf, encoded_data, encoded_data_len);
Added extra checks of encoded_data_len

2024-01-24 12:17 UTC, dragos-oancea approved these changes

2024-01-24 13:36 UTC, andywolk approved these changes

2024-01-24 13:37 UTC, jakubkarolczyk approved these changes

2024-01-24 13:50 UTC, merged

2024-04-23 13:46 UTC, olofssonanton commented on src/mod/codecs/mod_amrwb/mod_amrwb.c
> +	memcpy(buf, encoded_data, encoded_data_len);
@andywolk @dkunilov I've detected a case where the `encoded_data_len > SWITCH_AMRWB_OUT_MAX_SIZE` comparison causes calls to be hung up during a re-INVITE where the other party responds with multiple codecs in their 200 OK.

Alice and Bob are in a call using PCMA, and FreeSWITCH sends a re-INVITE to Alice. Alice responds with all codecs she accepts, with AMR-WB at the top. FreeSWITCH momentarily assumes the call is switching to AMR-WB, but Alice continues to send PCMA. With the changes from this PR, FreeSWITCH hangs up the call after `switch_amrwb_decode` returns `SWITCH_STATUS_FALSE`. Here's a log excerpt:

> 2024-04-23 13:12:44.593843 91.27% [DEBUG] sofia.c:8524 Processing updated SDP
2024-04-23 13:12:44.593843 91.27% [DEBUG] switch_core_media.c:8654 Audio params are unchanged for sofia/foo/Alice@X.X.X.X.
2024-04-23 13:12:44.593843 91.27% [DEBUG] switch_core_media.c:3644 Changing Codec from PCMA@20ms@8000hz to AMR-WB@20ms@16000hz
2024-04-23 13:12:44.613817 91.27% [DEBUG] switch_rtp.c:4437 RE-Starting timer [soft] 320 bytes per 20ms
2024-04-23 13:12:44.613817 91.27% [DEBUG] switch_core_media.c:3743 Set Codec sofia/foo/Alice@X.X.X.X AMR-WB/16000 20 ms 320 samples 23850 bits 1 channels
2024-04-23 13:12:44.613817 91.27% [DEBUG] switch_core_codec.c:124 sofia/foo/Alice@X.X.X.X Original read codec replaced with AMR-WB:110
2024-04-23 13:12:44.654008 91.27% [DEBUG] switch_core_media.c:3199 alternate payload received (received 8, expecting 96)
2024-04-23 13:12:44.654008 91.27% [WARNING] switch_core_media.c:3210 Changing current codec to PCMA (payload type 8).
2024-04-23 13:12:44.654008 91.27% [ERR] switch_core_media.c:16066 Codec AMR-WB / Bandwidth Efficient decoder error!
2024-04-23 13:12:44.654008 91.27% [DEBUG] switch_ivr_bridge.c:819 sofia/foo/Bob ending bridge by request from write function

I have not yet deduced what the encoded_data actually contains, if it actually inserts the PCMA payload into the AMR-WB decoder or what's going on, but I have tested the same case without mod_amrwb loaded (so it momentarily chooses g722) and that works perfectly.

2024-04-23 14:32 UTC, olofssonanton commented on src/mod/codecs/mod_amrwb/mod_amrwb.c
> +	memcpy(buf, encoded_data, encoded_data_len);
A description of how I encountered this:

1. Incoming call from Alice to FreeSWITCH, with Alice offering AMR-WB, G722, AMR, PCMA, PCMU.
2. Alice is bridged to Bob, using late negotiation.
3. Bob answers with PCMA.
4. FreeSWITCH connects Bob with Alice, both using PCMA.
5. FreeSWITCH sends re-INVITEs to both Alice and Bob, containing only PCMA.
6. Alice detects no change in SDP, so she answers with her previous offer (the initial offer, containing _all_ codecs).
7. FreeSWITCH seemingly tries to switch to AMR-WB, and the call breaks.

Alice's behaviour in step 6 is a bit puzzling to me, but I see nothing in any RFC which says it is incorrect.

2024-05-02 08:56 UTC, olofssonanton commented on src/mod/codecs/mod_amrwb/mod_amrwb.c
> +	memcpy(buf, encoded_data, encoded_data_len);
@andywolk @dkunilov I found out that the above re-INVITE sequence actually resulted in a PCMA payload being inserted into `encoded_data`. A fix for this is available in #2452.