mod_pgsql: err is now set correctly (dbh:last_error())
signalwire/freeswitch pull request #2374
Opened 2024-01-30 07:52 UTC by ar45

New function, `void pgsql_handle_set_error_if_not_set(switch_pgsql_handle_t *handle, char **err)` has been added to mod_pgsql module. This function is now called at several points where an error occurred but *err was not yet set.

2025-01-14 20:50 UTC, ar45 commented
@andywolk I rebased this. Can you please have this reviewed?

2025-01-14 21:03 UTC, andywolk requested changes

2025-01-14 21:03 UTC, andywolk commented on src/mod/databases/mod_pgsql/mod_pgsql.c
> +	pgsql_handle_set_error_if_not_set(handle, err);
Could you please add a new line before return.

2025-01-14 21:03 UTC, andywolk commented on src/mod/databases/mod_pgsql/mod_pgsql.c
> +	pgsql_handle_set_error_if_not_set(handle, err);
Could you please add a new line before return.

2025-01-14 21:03 UTC, andywolk commented on src/mod/databases/mod_pgsql/mod_pgsql.c
> +	pgsql_handle_set_error_if_not_set(handle, err);
Could you please add a new line before return.

2025-01-17 15:51 UTC, andywolk approved these changes

2025-01-17 15:51 UTC, merged