[mod_timerfd] Fixed - continue timer loop after receiving a SIGSTOP
signalwire/freeswitch pull request #2476
Opened 2024-06-05 21:20 UTC by ar45

When taking a snapshot of a machine which pauses the process, mod_timerfd runtime thread exits, causing all channels to wait indefinitely.

Check `errno == EINTR` and continue the timer loop.

2025-01-14 21:53 UTC, ar45 commented
@andywolk can you review this one?

Thank you!

2025-01-14 21:55 UTC, andywolk requested changes

2025-01-14 21:55 UTC, andywolk commented on src/mod/timers/mod_timerfd/mod_timerfd.c
> +			// if we had a interupted system call due to process pause via SIGSTOP, do not exit the timer loop
Please use `/* */` comment style.

2025-01-14 21:55 UTC, andywolk commented on src/mod/timers/mod_timerfd/mod_timerfd.c
> +		}
Could you please add a new line before loop

2025-01-15 21:19 UTC, andywolk requested changes

2025-01-15 21:19 UTC, andywolk commented on src/mod/timers/mod_timerfd/mod_timerfd.c
>  #include <switch.h>
Please try having `switch.h` to be first in the list.

2025-01-16 16:12 UTC, andywolk approved these changes

2025-01-16 16:13 UTC, merged