[mod_spandsp] Fix compilation against >=2023/06/02 spandsp
signalwire/freeswitch pull request #2668
Opened 2024-12-17 15:30 UTC by pfournier

This patch from my colleague allows FreeSWITCH to compile with latest or earlier spandsp code base:

spandsp, beginning with commit d9681c37 and coinciding with the SPANDSP_RELEASE_DATE of 20230620, introduced the following changes to its V.18 protocol API, which FreeSWITCH is not able to compile against:
- Certain V.18 constants were renamed.
- The v18_init function now requires passing a third function, handling the V.18 modem's status changes.

This patch allows FreeSWITCH to build against current versions of spandsp by:
- Using the new V.18 constant names.
- Implementing a simple status reporter callback function and passing it as the third function to v18_init.

Additionally, it retains backward compatibility with prior versions of spandp through #if conditions checking the value of SPANDSP_RELEASE_DATE.

2024-12-19 20:19 UTC, andywolk requested changes

2024-12-19 20:19 UTC, andywolk commented on src/mod/applications/mod_spandsp/mod_spandsp_dsp.c
> +	tdd_state = v18_init(NULL, TRUE, get_v18_mode(session), V18_AUTOMODING_GLOBAL, put_text_msg, NULL, handle_v18_status, NULL);
user data is null and will crash in handle_v18_status due to a null pointer dereference?

2025-01-13 14:23 UTC, andywolk commented on src/mod/applications/mod_spandsp/mod_spandsp_dsp.c
> +	tdd_state = v18_init(NULL, TRUE, get_v18_mode(session), V18_AUTOMODING_GLOBAL, put_text_msg, NULL, handle_v18_status, NULL);
@pfournier ping

2025-02-03 10:52 UTC, morbit85 approved these changes

2025-02-04 10:57 UTC, andywolk approved these changes

2025-02-04 16:05 UTC, pfournier commented
Thanks Andy for catching that, I approve your changes.

2025-02-04 20:54 UTC, merged