fix mod_av record crash bug
signalwire/freeswitch pull request #823
Opened 2020-08-27 01:53 UTC by mangshe0

fix mod_av record crash bug
it will lead ffmpeg-4.1\libavformat\utils.c(4424): if (s->url) {
av_freep(&s->url);
}
this time freep will dump.

recommit after seven du tutorial, thank you for that

2020-08-27 02:23 UTC, seven1240 commented
you don't need to create a new pr, reopen the old one and `push -f` to the old branch so we don't lose context.

2020-08-27 02:28 UTC, mangshe0 commented
wow, new skill, get it.

2020-08-27 03:31 UTC, seven1240 commented
is it possible to reopen and fix #820? any way, please add `[mod_av]` to the commit message

2020-08-28 01:55 UTC, mangshe0 commented
i`m sorry,  can`t recovery 820, 
alreadly modify the commit message add [mod_av] .

2020-12-16 23:55 UTC, seven1240 submitted a review, later dismissed

2020-12-17 12:02 UTC, andywolk requested changes

2020-12-17 12:02 UTC, andywolk commented on src/mod/applications/mod_av/avformat.c
> -		s->url = strdup(filename);
Why not just `av_strdup(filename)` ?

2020-12-22 16:17 UTC, andywolk commented
@mangshe0 ping. Let me know if you have any issue with this.

2020-12-23 16:30 UTC, andywolk approved these changes

2020-12-23 16:38 UTC, merged